title: Ajna Pleho
logo: /assets/img.jpg
description: Extrovert who is open to new inventions and opportunities.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

